export enum ReservationStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED_BY_TRANSACTION = 'CANCELLED_BY_TRANSACTION',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
  CANCELLED_BY_MANAGER_OR_OWNER = 'CANCELLED_BY_MANAGER_OR_OWNER',
}
